service: comment-platform
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
functions:
  getPosts:
    handler: pages/api/posts.handler
    events:
      - http:
          path: api/posts
          method: get
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Posts
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST